wallpaper {
    monitor = eDP-1
    path = /home/$USER/.config/hyprlandThemes/NoOneWillKnow/Backgrounds//Background5.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/$USER/.config/hyprlandThemes/NoOneWillKnow/Backgrounds//Background5.jpg
    fit_mode = cover
}
