wallpaper {
    monitor = eDP-1
    path = /home/psyamen/.config/hyprlandThemes/HollowKnight/Backgrounds/Background5.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/psyamen/.config/hyprlandThemes/HollowKnight/Backgrounds/Background5.jpg
    fit_mode = cover
}
